version: '3.7'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.7
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    command: meilisearch --db-path /meili_data --http-addr '0.0.0.0:7700'
