/*
 Skimlinks javascript runtime
 Copyrights 2009 - 2018

 Build time: Mon, 22 Jan 2018 08:43:53 GMT
 Version: 13.1.2
*/
(function(){function hc(a){var b;var c=b=null;var d=5;a.Limit&&(d=a.Limit);var e=function(){return a.Priority||0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return d-1},limit:function(){return d},action_type:function(){return a.ActionType},text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},is_editor:function(){return null!=a.ValidOn&&""!==a.ValidOn?!0:!1},is_blacklisted:function(){return null!=
a.IsBlacklisted?a.IsBlacklisted:!1},group_priority:function(){return b?b.group_priority():e()},id:function(){return c?c:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?"":null!=a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){return a.Unlinked?a.Title="":a.Title=b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=a},set_id:function(a){return c=a}}}function Wa(a,b){return 0===b.length?
!1:sa(a,b.join(","))?!0:a.parentNode?Wa(a.parentNode,b):!1}function Xa(a,b){var c=a.style.cssText;""!==c&&(c+=" ");var d=l("link_background");d&&(-1===d.indexOf("#")&&(d="#"+d),c+="background-color: "+d+" !important; ");null!==l("link_tooltip",null)&&(a.title=l("link_tooltip"));b&&(ta&&(d=ta,-1===d.indexOf("#")&&(d="#"+d),c+="color: "+d+" !important; "),ua&&(c+="font-weight: "+ua+" !important; "),R&&(c="double"===R?c+"border-bottom: 1px double !important; ":"dashed"===R?c+"border-bottom: 1px dashed !important; ":
c+("text-decoration: "+R+" !important; ")),va&&(c+="font-style: "+va+" !important; "),l("skimwords_link_style")&&(d=l("skimwords_link_style"),c+=d+"; "),l("skimwords_link_class")&&(a.className=y(a.className+" "+l("skimwords_link_class"))),wa&&(a.title=wa),null===a.getAttribute("title")&&(a.title="Shopping link added by SkimWords"),a.getAttribute("data-skim-creative")&&(d=parseInt(a.getAttribute("data-skim-creative"))%10,1===d||2===d))&&(a.title="");a.style.cssText=c;return!0}function xa(a){var b;
a=a.target||a.srcElement;var c=null!=a?null!=(b=a.nodeName)?"function"===typeof b.toUpperCase?b.toUpperCase():void 0:void 0:void 0;"A"!==c&&"AREA"!==c&&(a=Ya(a));return a}function ic(a){var b;n.event&&(a=n.event);var c=a.originalTarget||a.srcElement||a.target;var d=null!=c?c.nodeName.toUpperCase():void 0;"A"!==d&&"AREA"!==d&&(c=jc(c));(d=!c||Za(c))||(d=u(c,"rel"),d=!(S?S===d:!d||!$a(d)));if(d)return!0;var e=y(c.href);d=M(c.hostname);var f="click"===a.type||"contextmenu"===a.type;if(b=ab)if(b=c,null===
b.offsetParent)b=!0;else{var g=n.getComputedStyle;b=p(g)?"hidden"===g(b).visibility:!1}g=(g=c)&&g.href?/^https?:\/\//.test(g.href)||/^\/\//.test(g.href):!1;if(g&&ya(c.href,d)&&!b){if(bb(d)||kc(d))cb(c,a);else if(f&&db(e)&&!eb(d))return H&&u(c,"target",H),lc(a);return!0}}function ba(a){var b=xa(a);if(!b)return!0;var c=b;c&&c.nodeName&&"A"!==c.nodeName.toUpperCase()&&"AREA"!==c.nodeName.toUpperCase()&&(c=Ya(c));if(c){var d=mc(c);var e=k.waypointDomain;if(!(d.length>=e.length&&d.substr(0,e.length)===
e)){e=-1!==d.indexOf(e)?d:nc(c,d);if(fb){var f=l("pageTracker");var g="/skimout/"+d;null!=f&&f._trackPageview?f._trackPageview(g):l("_gaq")?(f=l("_gaq"),f.push(["_trackEvent","skimout","click",d])):l("ga")&&l("ga")("send","event","click","skimout",d)}gb(c);hb(c,e)}}c=l("skimlinks_keywee_pixel",null);e=-1<n.location.href.indexOf("utm_campaign=fbkw");c&&e&&ib(c);l("vglnk")&&I(b,"skimwords-link")&&(a&&a.stopPropagation?a.stopPropagation():(a=n.event,a.cancelBubble=!0));return!0}function Ya(a){for(;a.parentNode;){a=
a.parentNode;var b=a.nodeName.toUpperCase();if("A"===b||"AREA"===b)return a}return null}function ca(a,b){var c={data:x({pubcode:A,domains:a,page:n.location.href})};za(c);oc(a,b);return!0}function jb(){var a;var b=da();var c=[];var d=0;for(a=b.length;d<a;d++){var e=b[d];var f=M(e.hostname);var g=y(e.href);e=u(e,"rel");!f||!ya(g,f)||(S?S!==e:e&&$a(e))||T(f)||void 0!==k.aff_domains[f]||(c.push(f),k.domain_data.domains.push(f),k.aff_domains[f]=null)}return c}function pc(a){return Aa(a,"beacon_callback_aux")}
function qc(a){Aa(a,"beacon_callback_post_page_load");return kb()}function rc(a){return Aa(a,"beacon_callback_pre_page_load")}function kb(a){var b,c;a||(a=0);if(n.skimlinks_requests_in_flight&&5>a)setTimeout(function(){return kb(a+1)},400*a);else{var d=da();var e=b=0;for(c=d.length;e<c;e++){var f=d[e];var g=y(f.href);var w=M(f.hostname);var h=u(f,"class");(!h||-1===h.indexOf("skimwords-link")&&-1===h.indexOf("skimlinks-unlinked"))&&ya(g,w)&&!sc(f)&&(bb(w)?(b++,C(m.link_impressions,g)?m.link_impressions[g].ae=
1:m.link_impressions[g]={count:0,ae:1}):C(m.link_impressions,g)||(m.link_impressions[g]={count:0,ae:0}),m.link_impressions[g].count++,f=tc(g))&&(m.link_impressions[g].slmcid=f,0>uc.call(m.campaign_ids,f)&&m.campaign_ids.push(f))}k.handlers=b;k.links_tracked||null==lb||null==k.domain_data||null==k.domain_data.domains||(k.links_tracked=!0,lb(k.domain_data.domains));ea("skimlinks")}return!0}function N(a,b,c){for(null==c&&(c=!1);null!=a&&a!==k.html_root;){var d=I(a,b)||I(a,"noskim");if(a.className&&d)return!0;
a=c?null:a.parentNode}return!1}function eb(a){null!==k.exclude_lookup&&null!==k.include_lookup||mb();if(!a)return!1;var b=k.exclude_lookup;for(d in b)if(nb.call(b,d)){var c=b[d];if(0===d.indexOf("*")){var d=d.substr(1);--c;var e=a.lastIndexOf(d);if(-1!==e&&e===a.length-c)return!0}else if(a===d)return!0}return!1}function sc(a){var b=ob.join(", ");if(!a&&!b)return!1;var c=Boolean,d;if(d=b)a:if(p(window.Element.prototype.closest))d=a.closest(b);else{for(;a&&1===a.nodeType;){d=a;var e=b,f=window.Element.prototype;
f=f.matches||f.msMatchesSelector||f.mozMatchesSelector||f.webkitMatchesSelector;if(p(f))d=f.call(d,e);else{e=vc(d.document||d.ownerDocument,e);for(f=0;e[f]&&e[f]!==d;)f+=1;d=!!e[f]}if(d){d=a;break a}a=a.parentNode}d=null}return c(d)}function ya(a,b){var c;if(c=l("_merchantSettings"))c=-1!==b.indexOf("itunes.apple.com")||-1!==b.indexOf("itunes.com")||-1!==b.indexOf("phobos.apple.com");return c||eb(b)?!1:db(a)&&wc(b)}function bb(a){return J?(pb(a)&&(k.handlers+=1),!1):pb(a)}function Za(a){for(var b,
c,d,e,f;a&&a!==k.html_root;){d=a.id;c=0;for(e=U.length;c<e;c++)if(b=U[c],I(a,b))return!1;f=k.included_ids;c=0;for(e=f.length;c<e;c++)if(b=f[c],d===b)return!1;e=k.excluded_classes;d=0;for(c=e.length;d<c;d++)if(b=e[d],I(a,b))return!0;a=a.parentNode}return U.length||k.included_ids.length?!0:!1}function da(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:q,c=null;a&&(c=new RegExp("\\b"+qb(a)+"\\b","i"));var d=Ba(b.getElementsByTagName("a"));b=Ba(b.getElementsByTagName("area"));d=d.concat(b);
return Ca(d,function(a,b){b.href&&(!c||b.className&&c.test(b.className))&&a.push(b);return a},[])}function ea(a){var b;if(!Da||rb)return!1;m.tracking[a]=!1;a=!0;var c=m.tracking;for(b in c)if(sb.call(c,b)){var d=c[b];if(!0===d){a=!1;break}}if(a)return rb=!0,xc()}function lb(){if(!Da)return!1;var a=tb(A,n,h,k,m);a={data:x(a)};v&&(a.dnt=v);B&&(a.fdnt=1);a=za(a);if(h.isAdblockUser||!ub("//t.skimresources.com/api/link",a,vb))return yc()}function ub(a,b,c){if("msie"!==h.detect.browser){var d=!1;var e=
new XMLHttpRequest;e.open("POST",a,!0);e.setRequestHeader("Content-type","application/x-www-form-urlencoded");0<=wb.call(e,"withCredentials")&&(e.withCredentials=!0);e.async="true";e.onreadystatechange=function(){if(d)return!0;if(4===e.readyState){d=!0;if(200===e.status){var a={};var b=e.responseText;if(0===b.indexOf("//"))return c(a),!0;try{a=xb(e.responseText)}catch(zd){}c(a);return!0}return!1}};e.send(b)}else if(n.XDomainRequest){var f=new XDomainRequest;0<=wb.call(f,"withCredentials")&&(f.withCredentials=
!0);if(f){f.open("POST",a,!0);f.onload=function(){var a={};if(0===f.responseText.indexOf("//"))return c(a),!0;try{a=xb(f.responseText)}catch(w){}c(a);return!0};f.onerror=function(){return!1};f.onprogress=function(){return!1};f.ontimeout=function(){return!1};f.async=!0;try{f.send(b)}catch(g){return!1}}}else return!1;return!0}function za(a){var b;var c=[];J&&(a.xrf=1);for(b in a)C(a,b)&&c.push(""+b+"="+t(a[b]));return c.join("&")}function fa(a,b,c,d,e){var f;null==c&&(c={});var g=c.charset||null;var w=
c.target||null;c=null!=(f=c.async)?f:!0;f=null!=w&&w.document?w.document:document;var h=f.getElementsByTagName("head")[0];var k=f.createElement("script");k.type="text/javascript";g&&(k.charset=g);b&&(k.onload=k.onreadystatechange=function(a){return function(){var c=!1;return function(){var d=a.readyState;if(!(c||d&&"complete"!==d&&"loaded"!==d))return k.onload=k.onreadystatechange=null,c=!0,b.call(w),!0}}}(this)());k.onerror=function(){if(null!=d)return null!=e?d(e):d(!1)};k.async=!1!==c;k.src=a;
h.appendChild(k);return k}function M(a){return a.replace(/^www\./i,"")}function zc(){for(var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],b=arguments[1],c=arguments[2],d=0;d<a.length;d++){var e=yb(a[d]);if(!O(e))return p(c)?c(e,b):e}return b}function yb(a,b,c){return O(n[a])?b:p(c)?c(n[a],b):n[a]}function l(a,b,c){return Ea(a)?zc(a,b,c):yb(a,b,c)}function O(a){return"undefined"===typeof a||null===a}function Ea(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}
function p(a){return"[object Function]"===Object.prototype.toString.call(a)}function Fa(a,b){if(p(a.indexOf))return a.indexOf(b);if(Ea(a))for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1}function Ac(){var a=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"";return 0===Fa((0<arguments.length&&void 0!==arguments[0]?arguments[0]:"").slice(2<arguments.length&&void 0!==arguments[2]?arguments[2]:0),a)}function zb(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",b=1<arguments.length&&
void 0!==arguments[1]?arguments[1]:"",c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0;c=c<a.length?c|0:a.length;return a.substr(c-b.length,b.length)===b}function V(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,c=q.createElement("a");c.href=b?a:Bc(a);try{return M(c.hostname)}catch(d){return""}}function Bc(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"http",c="";/^https?:\/\//.test(a)||/^\/[^/]+/.test(a)||(c=/^\/\//.test(a)?b+":":b+"://");return""+
c+a}function db(a){var b=V(a,1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0),c=k.hostname,d=zb(b,"."+c)||zb(c,"."+b);return b!==c&&!d}function Ab(a){return Ga?Ga:"msie"===h.detect.browser&&8>=h.detect.version||a?"//go.redirectingat.com":"//go.skimresources.com"}function T(a){return-1!==k.waypointDomain.indexOf(a)||-1!==a.indexOf("go.redirectingat.com")||-1!==a.indexOf("go.skimresources.com")}function C(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function W(a){return 10>a?"0"+
a:""+a}function Ha(){return this.valueOf()}function Ia(a){Ja.lastIndex=0;return Ja.test(a)?'"'+a.replace(Ja,function(a){var b=Bb[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function ha(a,b){var c,d=void 0,e=r,f=b[a];f&&"object"===typeof f&&p(f.toJSON)&&(f=f.toJSON(a));p(D)&&(f=D.call(b,a,f));switch(typeof f){case "string":return Ia(f);case "number":return isFinite(f)?String(f):"null";case "boolean":case "null":return String(f);case "object":if(!f)return"null";
r+=ia;var g=[];if(Ea(f)){var w=f.length;for(c=0;c<w;c+=1)g[c]=ha(c,f)||"null";var h=0===g.length?"[]":r?"[\n"+r+g.join(",\n"+r)+"\n"+e+"]":"["+g.join(",")+"]";r=e;return h}if(D&&"object"===typeof D)for(w=D.length,c=0;c<w;c+=1)"string"===typeof D[c]&&(d=D[c],(h=ha(d,f))&&g.push(Ia(d)+(r?": ":":")+h));else for(d in f)C(f,d)&&(h=ha(d,f))&&g.push(Ia(d)+(r?": ":":")+h);h=0===g.length?"{}":r?"{\n"+r+g.join(",\n"+r)+"\n"+e+"}":"{"+g.join(",")+"}";r=e;return h}}function x(a,b,c){if(window.JSON&&p(JSON.stringify))return JSON.stringify.apply(null,
arguments);Cb();var d;ia=r="";if("number"===typeof c)for(d=0;d<c;d+=1)ia+=" ";else"string"===typeof c&&(ia=c);if((D=b)&&!p(b)&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return ha("",{"":a})}function xb(a,b){function c(a,d){var e=void 0,f=a[d];if(f&&"object"===typeof f)for(e in f)if(C(f,e)){var h=c(f,e);void 0!==h?f[e]=h:delete f[e]}return b.call(a,d,f)}if(window.JSON&&p(JSON.parse))return JSON.parse.apply(null,arguments);Cb();var d=void 0;a=String(a);Ka.lastIndex=
0;Ka.test(a)&&(a=a.replace(Ka,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(Cc.test(a.replace(Dc,"@").replace(Ec,"]").replace(Fc,"")))return d=(0,eval)("("+a+")"),p(b)?c({"":d},""):d;throw new SyntaxError("JSON.parse");}function Gc(a){a.width=0;a.height=0;a.style.display="none"}function Db(){return(0<arguments.length&&void 0!==arguments[0]?arguments[0]:q).getElementsByTagName("body")[0]}function ib(a,b){P||(P=q.createElement("iframe"),Db().appendChild(P),Gc(P));var c=
P.contentDocument||P.contentWindow.document,d=Db(c);d||(d=q.createElement("body"),c.appendChild(d));c=c.createElement("img");c.src=a;c.width=1;c.height=1;b&&p(b)&&(c.onload=function(){b()});d.appendChild(c)}function ja(a,b){for(var c=0;c<a.length;c++)b(a[c],c,a)}function y(a){return O(a)?"":a.toString().replace(/^[\s\xA0]+|[\s\xA0]+$/g,"")}function u(a,b,c){3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{var d=a[b];d||(d=a.getAttribute(b));return d}catch(e){return null}}
function tb(a,b,c,d,e){return{dl:e.link_impressions,guid:c.cookie,hae:d.handlers?1:0,pag:b.location.href,pub:a,sessid:c.sessid,slmcid:e.campaign_ids,typ:"l",tz:c.timezone,uuid:c.uuid}}function Ca(a,b,c){for(var d=0,e=null===a?0:a.length;d<e;)c=b(c,a[d],d,a),d+=1;return c}function Ba(a){return Ca(a,function(a,c){return a.concat(c)},[])}function Eb(a,b){var c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:!1,d=document.createElement("div"),e="qsa"+String(Math.random()).slice(3);d.innerHTML=
"x<style>"+b+"{qsa:"+e+";}";d=Fb.appendChild(d.lastChild);e=Gb(a,b,c,e);Fb.removeChild(d);return c?e[0]:e}function Gb(a,b,c,d){var e=/1|9/.test(a.nodeType),f=a.childNodes,g=[],h=0;if(e&&a.currentStyle&&a.currentStyle.qsa===d&&g.push(a)&&c)return g;for(;(a=f[h])&&(g=g.concat(Gb(a,b,c,d)),h+=1,!c||!g.length););return g}function vc(a,b){1===arguments.length&&"string"===typeof a&&(b=a,a=q);return p(a.querySelectorAll)?Ba(a.querySelectorAll(b)):Eb(a,b,!1)}function I(a,b){return a&&a.className&&b?0<=Fa(y(a.className).split(/\s+/),
b):!1}function Hc(a,b){var c=!1,d=void 0;return function(){if(c)return d;setTimeout(function(){c=!1},b);c=!0;return d=a.apply(this,arguments)}}function hb(a,b){if(a){var c=null,d=a.childNodes.length&&3===a.childNodes[0].nodeType;"msie"===h.detect.browser&&d&&(c=a.innerHTML);a.href=b;c&&c!==a.innerHTML&&(a.innerHTML=c)}}function gb(a){if(!a||!a.sl_href_restore_scheduled){var b=a.href,c="msie"===h.detect.browser&&7>h.detect.version?1E4:Hb;a.sl_href_restore_scheduled=!0;setTimeout(function(){a.href=
b;delete a.sl_href_restore_scheduled},c)}}function ka(a){if(O(a))return[];var b=[],c;for(c in a)C(a,c)&&b.push(c);return b}function La(a,b){return-1!==Fa(a,b)}function Ma(a){return String(a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function Ic(){var a=la.settings;2===a.nc?h.unlinkedEnabled&&ca(k.domain_data.domains,"skimlinksBeaconAuxCallback"):h.unlinkedEnabled&&(a.includes?(E&&E.length&&(a.excludes=a.excludes.concat(E)),F.traverse(a.includes,a.excludes,
a.read_onlys)):E&&E.length?F.traverse(["body"],E,[]):F.traverse(["body"],[],[]));Ib()}function Ib(){a:{var a=q.getElementsByTagName("body");if(a.length){a=a[0].textContent||a[0].innerText;var b;if(b=a)a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig.exec(a),b=a.length&&""!==a[0]?!0:!1;if(b){a=!0;break a}}a=!1}a?(h.skimwordsEnabled||F.traverse([],E,[]),Jb()):ea("unlinked")}function Jb(){var a;var b=F.get_as_hash_node_dict();var c={};for(g in b){var d=b[g];
if(d.parentNode&&!(Za(d)||N(d,"noskimwords")||N(d,"noskimlinks")||N(d,"noskimw")||d.meta&&d.meta.ReadOnly)){d=Jc(d,g);var e=d[0];var f=0;for(a=e.length;f<a;f++)d=e[f],!c[d]&&Kc(d)&&(c[d]=!0,k.domain_data.domains.push(d))}}var g=ka(c);g.length?ca(g,"skimlinksBeaconAuxCallback"):ea("unlinked")}function Lc(){ka(k.aff_domains).length&&(ja(ma.url_spans,function(a){if(k.aff_domains[a.match.domain]){var b=a.node;a=a.match;var c=a.phrase;var d={};d.w=c.text();d.lp=c.url();d.t=ma.creative;var e;var f=!0;var g=
m.unlinked_impressions;c=0;for(e=g.length;c<e;c++){var h=g[c];h.w===d.w&&(f=!1)}f&&m.unlinked_impressions.push(d);X++;Mc(b,a,!0)}}),setTimeout(function(){var a;var b=da("skimlinks-unlinked");var c=[];var d=0;for(a=b.length;d<a;d++){var e=b[d];c.push(Nc(e))}return c},10));ea("unlinked")}function Kb(a,b){Q||1E3<b?p(a)&&(Q?Na?a(!0):a(!1):a(!1)):setTimeout(Kb,b*=2,a,b)}function Lb(){Q||(Y.complete&&Z.complete&&(Q=!0),Q&&"0"!=Y.width&&"0"==Z.width&&(Na=!0))}function Oc(a,b){1===arguments.length&&"string"===
typeof a&&(b=a,a=q);return p(a.querySelector)?a.querySelector(b):Eb(a,b,!0)}function Pc(a,b){if(!a)return[];if(!b)return[].concat(a);var c=[];ja(a,function(d,e){c.push(b(d,e,a))});return c}function Qc(a){function b(a){return a.toLowerCase().replace(/^\/\/|^https?:\/\//,"")}var c=Pc(Mb,b);return La(c,b(a))}function Rc(){var a=arguments[0],b=Array.prototype.slice.call(arguments,1);O(a)&&(a={});ja(b,function(b){O(b)&&(b={});Ca(ka(b),function(a,c){a[c]=b[c];return a},a)});return a}function Sc(){return{skimOptions:Tc,
runTimeInfo:Rc({},{aff_domains:k.aff_domains},h)}}var Nb=window.skimlinks_context_window||null,n=Nb?window[Nb]:window,q=n.document,Uc=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1},z={topics:{},on:function(a,b){var c;null==(c=this.topics)[a]&&(c[a]=[]);return this.topics[a].push(b)},off:function(a,b){var c=0<=Uc.call(this.topics[a],b);if(-1<c)return this.topics[a].splice(c,1)},once:function(a,b){var c=function(a){return function(){c.called||
b.apply(a,arguments);return c.called=!0}}(this);c.called=!1;return this.on(a,c)},publish:function(a,b){var c;var d={topic:a,extra:b};if(this.topics[a]){var e=this.topics[a];var f=[];var g=0;for(c=e.length;g<c;g++){var h=e[g];f.push("function"===typeof h?h(d):void 0)}return f}}},Vc="*.g.doubleclick.net *mjxads.internet.com *pgpartner.co.uk *pgpartner.com *pricegrabber.co.uk *pricegrabber.com *overture.com *youtube.com paid.outbrain.com trc.taboola.com traffic.outbrain.com zergnet.com *.criteo.com track.celtra.com".split(" "),
Oa=/https?:/g,Pa=q.createTextNode("").nodeName,Wc=["noskim","norewrite"],Qa={"t.umblr.com":{name:"z"}},A="725X1342",Ob="1342",Ra=l("noskim",!1),Xc=l("noskimlinks",!1),Yc=l("noskimwords",!0),Zc=l("nounlinked",!1),$c=l("skimwords_standard",false),ad=l("skimwords_lite",false),bd=l("skimwords_diy",false),cd=l("skimwords_diy_filter",false),Pb=!Ra&&!Xc,Qb=!Ra&&
!Yc,Rb=!Ra&&!Zc,v=l("skimlinks_dnt",0,function(a){return a&&"0"!==a&&"false"!==a?1:0}),B=l("skimlinks_nocookie",!1),U=l("skimlinks_included_classes",[]),Sb=l("skimlinks_excluded_classes",[]),Tb=l("skimlinks_exclude",[]),Ub=l("skimlinks_include",[]),Vb=l("skimlinks_included_ids",[]),Sa=l("skimlinks_exrel",""),
S=l("skimlinks_byrel",!1),ab=l("skimlinks_ignore_hidden_links",false),ob=l("skimlinks_link_impression_exclude_selector",[]),Wb=l("skimlinks_add_nofollow",false),Xb=l("skimlinks_before_click_handler",false,function(a,b){return"boolean"!==typeof a?b:a}),Yb=l("skimlinks_first_party_na",!1),dd=l("skimlinks_cookie_sync_optout",!0),
Da=!l("noimpressions",!1),Hb=l("skimlinks_replace_timeout",300,function(a,b){var c=parseFloat(a);return isNaN(c)?b:c}),Zb=l("skimlinks_affiliate_unknown_links",true),H=l("skimlinks_target",null),ed=l("skimlinks_ajax_rerun",false),aa=l("sl_test",!1),E=[],J=l("skimlinks_revenue_forecast",false),$b=l("skimlinks_noright",
false),ac=l("skimlinks_url_extraction_rules",!1)||false,Ta=l("skimlinks_extra_redir_params",[]).join("&"),na=l(["affiliate_tracking","skimlinks_tracking"],!1,function(a,b){var c=/^[a-z0-9_\\|]+$/i;return a&&c.test(a)?a:b}),oa=l("force_location"),G=l(["skimlinks_site","skimlinks_sitename"],!1),bc=l("skimlinks_domain","wordpress.redirectingat.com"),Ga=bc?"http://"+bc:"",fb=l("skimlinks_google",false),
Mb=l("noskim_domains",[]),fd=l("skimwords_horizontal_distance",80),gd=l("skimwords_vertical_distance",80),cc=l("skimlinks_profiling",false),ta=l("skimwords_color",null),ua=l("skimwords_weight",null),R=l("skimwords_decoration",null),va=l("skimwords_style",null),wa=l("skimwords_title",
null),Ua=l("no_skim_selector",""),Tc=Object.freeze({SW_STANDARD:$c,SW_LITE:ad,SW_DIY:bd,SW_DIY_FILTER:cd,HAS_SKIMLINKS:Pb,HAS_SKIMWORDS:Qb,HAS_UNLINKED:Rb,DO_NOT_TRACK:v,NO_COOKIE:B,SL_INCLUDED_CLASSES:U,SL_EXCLUDED_CLASSES:Sb,SL_EXCLUDED_DOMAINS:Tb,SL_INCLUDED_DOMAINS:Ub,SL_INCLUDED_IDS:Vb,SL_EXCLUDED_REL:Sa,SL_INCLUDED_REL:S,SL_IGNORE_HIDDEN_LINKS:ab,SL_IMPRESSION_EXCLUDED_SELECTORS:ob,SL_ADD_NOFOLLOW:Wb,SL_BEFORE_CLICK_HANDLER:Xb,SL_FIRST_PARTY_NA:Yb,
SL_COOKIE_SYNC_OPTOUT:dd,SL_TRACK_IMPRESSION:Da,SL_REPLACE_TIMEOUT:Hb,SL_AFFILIATE_UNKNOWN_LINKS:Zb,SL_TARGET:H,AJAX_SUPPORT:ed,SL_TEST:aa,UNLINKED_EXCLUDES:E,SL_FORECAST:J,NO_RIGHT_CLICK:$b,USE_MERCHANT_URL_EXTRACTION_RULES:ac,EXTRA_REDIR_PARAMS:Ta,CUSTOM_TRACKING_VAR:na,FORCE_LOCATION:oa,SITE_NAME:G,CUSTOM_WAYPOINT_DOMAIN:Ga,TRACKING_GOOGLE:fb,NO_SKIM_DOMAINS:Mb,SW_HORIZONTAL_DISTANCE:fd,SW_VERTICAL_DISTANCE:gd,SL_PROFILING:cc,SW_LINK_COLOR:ta,SW_LINK_WEIGHT:ua,SW_LINK_DECORATION:R,SW_LINK_STYLE:va,
SW_LINK_TITLE:wa,NO_SKIM_SELECTOR:Ua}),h=function(){var a=q.referrer||document.referrer||"",b=oa||n.location.href;var c="aspsession-id aspsessionid cftoken j-sessionid jsessid jsession_id jsessionid phpsessid phpsession-id phpsessionid seskey sessid session-id session-key session_id sessionid sessionkey uniqueid utm_campaign utm_medium utm_source utm_term".split(" ");for(var d=0;d<c.length;d++){var e=c[d];var f=b.split("?");if(2<=f.length){b=f.shift();f=f.join("?");e=encodeURIComponent(e)+"=";f=f.split(/[&;]/gi);
for(var g=f.length-1;0<=g;g--)Ac(f[g],e)&&f.splice(g,1);b=b+"?"+f.join("&")}}"?"===b[b.length-1]&&(b=b.substr(0,b.length-1));c=b;d=navigator.userAgent.toLowerCase();d=/(webkit)[ /]([\w.]+)/.exec(d)||/(opera)(?:.*version)?[ /]([\w.]+)/.exec(d)||/(msie) ([\w.]+)/.exec(d)||0>d.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(d)||[];d={browser:d[1]||"",version:parseFloat(d[2])||0};b=(new Date).getTimezoneOffset();e="";for(f=0;8>f;f++)e+=Math.floor(65536*(1+Math.random())).toString(16).substring(1);
return{cookie:"",detect:d,isAdblockUser:!1,pageLocation:c,referrer:a,sessid:"",timezone:b,uuid:e,skimwordsEnabled:Qb,skimlinksEnabled:Pb,unlinkedEnabled:Rb}}(),m={campaign_ids:[],impressions:{pag:"",phr:[],unl:[],pub:A,slc:0,swc:0,ulc:0,jsl:0,jsf:"",guid:"",uuid:"",sessid:"",uc:na,t:1,slmcid:!1},link_impressions:{},loading_started:(new Date).getTime(),phrase_impressions:[],tracking:{skimlinks:!1,skimwords:!1,unlinked:!1},unlinked_impressions:[]},k=function(){var a=document.getElementsByTagName("html")?
document.getElementsByTagName("html")[0]:null,b=oa?V(oa,!1):n.location.hostname;return{aff_domains:{},beacon:[],callback_name:"skimlinksBeaconCallback",domain_data:{domains:[]},exclude:Tb,exclude_lookup:null,excluded_classes:["noskimlinks","noskim"].concat(Sb),handlers:0,has_been_called:!1,hostname:b,html_root:a,include:Ub,include_lookup:null,included_classes:U,included_ids:Vb,links:[],links_tracked:!1,target:null,waypointDomain:Ab()}}(),la={branded_merchant:!1,branded_merchant_url:!1,country:"",
data:void 0,debug:0,force_country:!1,force_domain_check:!1,force_tree:!1,handler_attached_hook:!1,handlers:0,hover_name:"dark",link_all:!1,lite:!1,maxproducts:3,merchant_excludes:!1,merchant_includes:!1,no_limit:!1,noVisual:!1,original_request:void 0,prio_threshold:0,request_counter:0,settings:null,send_in_progress:!1,this_page:n.location.href,x_min_visual_distance:80,y_min_visual_distance:80},ma={creative:"500005",url_spans:[]},Cc=/^[\],:{}\s]*$/,Dc=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,Ec=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
Fc=/(?:^|:|,)(?:\s*\[)+/g,Ja=/[\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,Ka=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,Cb=function(a){var b=!1,c=void 0;return function(){if(b)return c;c=a.apply(this,arguments);b=!0;return c}}(function(){p(Date.prototype.toJSON)||(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+
"-"+W(this.getUTCMonth()+1)+"-"+W(this.getUTCDate())+"T"+W(this.getUTCHours())+":"+W(this.getUTCMinutes())+":"+W(this.getUTCSeconds())+"Z":null});p(Boolean.prototype.toJSON)||(Boolean.prototype.toJSON=Ha);p(Number.prototype.toJSON)||(Number.prototype.toJSON=Ha);p(String.prototype.toJSON)||(String.prototype.toJSON=Ha)}),r=void 0,ia=void 0,Bb=void 0,D=void 0;Bb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};var wb=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in
this&&this[b]===a)return b;return-1},t=function(){var a;var b=[function(){var b;var d=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];var e=[];var f=0;for(b=d.length;f<b;f++)a=d[f],e.push([new RegExp(a[0],"g"),a[1]]);return e}()];return function(c){var d;var e=encodeURIComponent(c);c=0;for(d=b.length;c<d;c++)a=b[c],e=e.replace(a[0],a[1]);return e}}(),P=void 0,sb={}.hasOwnProperty;var rb=!1;var X=0;var yc=function(){var a;var b=8E3;"msie"===h.detect.browser&&
(b=2E3);var c=tb(A,n,h,k,m);c.dl={};var d="//t.skimresources.com/api/link?data=";var e=0;var f=m.link_impressions;for(a in f)if(sb.call(f,a)){var g=f[a];e++;c.dl[a]=g;g=d+t(x(c));g.length>b&&(e--,delete c.dl[a])}e&&(d+=t(x(c)),fa(d,!1,{async:!0}));return!0};var vb=function(){return!0};var pa=function(a){var b,c;if(a instanceof Array){var d={};var e=b=0;for(c=a.length;b<c;e=++b){var f=a[e];d[""+e]=f}return d}return a};var hd=function(){var a,b,c;var d=(new Date).getTime()-m.loading_started;var e=8E3;
"msie"===h.detect.browser&&(e=2E3);m.impressions.tz=h.timezone;m.impressions.slc=k.handlers;m.impressions.swc=null!=(a=la.handlers)?a:0;m.impressions.ulc=null!=X?X:0;m.impressions.jsl=d;m.impressions.guid=h.cookie;m.impressions.slmcid=m.campaign_ids;m.impressions.uuid=h.uuid;m.impressions.sessid=h.sessid;m.impressions.pref=h.referrer;m.impressions.phr=[];m.impressions.unl=[];J&&(m.impressions.xrf=1);d="//t.skimresources.com/api/track.php?";v&&(d+="dnt=1&");B&&(d+="fdnt=1&");h.isAdblockUser&&(d+="abp=1&");
d+="data=";var f=m.phrase_impressions;a=b=0;for(c=f.length;b<c;a=++b)a=f[a],m.impressions.phr.push(a),a=d+t(x(m.impressions).replace(Oa,"")),a.length>e&&(m.impressions.phr=m.impressions.phr.slice(0,-1));f=m.unlinked_impressions;a=b=0;for(c=f.length;b<c;a=++b)a=f[a],m.impressions.unl.push(a),a=d+t(x(m.impressions).replace(Oa,"")),a.length>e&&(m.impressions.unl=m.impressions.unl.slice(0,-1));m.impressions.phr=pa(m.impressions.phr);m.impressions.unl=pa(m.impressions.unl);e=d+t(x(m.impressions).replace(Oa,
""));return fa(e,!1,{async:!0})};var xc=function(){var a;var b=(new Date).getTime()-m.loading_started;m.impressions.tz=h.timezone;m.impressions.slc=k.handlers;m.impressions.swc=null!=(a=la.handlers)?a:0;m.impressions.ulc=null!=X?X:0;m.impressions.jsl=b;m.impressions.guid=h.cookie;m.impressions.slmcid=m.campaign_ids;m.impressions.uuid=h.uuid;m.impressions.sessid=h.sessid;m.impressions.pref=h.referrer;m.impressions.pag=h.pageLocation;m.impressions.phr=pa(m.phrase_impressions);m.impressions.unl=pa(m.unlinked_impressions);
b={data:x(m.impressions)};v&&(b.dnt=v);B&&(b.fdnt=1);b=za(b);!h.isAdblockUser&&ub("//t.skimresources.com/api/track.php",b,vb)||hd();return!0};z.on("skim_js_init",function(){m.tracking.skimlinks=h.skimlinksEnabled;m.tracking.skimwords=h.skimwordsEnabled;return m.tracking.unlinked=h.unlinkedEnabled});var qb=function(){var a=/[-[\]{}()*+?.,\\^$|#]/g,b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"\\s+")}}(),Fb=q.getElementsByTagName("head")[0],nb={}.hasOwnProperty,id=[].indexOf||function(a){for(var b=
0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1};var mb=function(){var a;k.exclude_lookup={};k.include_lookup={};G&&k.exclude.push(G);var b=k.exclude.concat(Vc);var c=0;for(a=b.length;c<a;c++){var d=b[c];k.exclude_lookup[d]=d.length}b=k.include;c=0;for(a=b.length;c<a;c++)d=b[c],k.include_lookup[d]=d.length;return k.exclude_lookup};var wc=function(a){null!==k.exclude_lookup&&null!==k.include_lookup||mb();if(!a)return!1;if(0===k.include.length)return!0;var b=k.include_lookup;for(e in b)if(nb.call(b,
e)){var c="*"===e.substr(0,1);var d="*"===e.substr(e.length-1,1);var e=e.replace(/\*/g,"");if(c&&d){if(-1!==a.indexOf(e))return!0}else if(c){if(-1!==a.indexOf(e)&&a.indexOf(e)===a.length-e.length)return!0}else if(d){if(0===a.indexOf(e))return!0}else if(a===e)return!0}return!1};var pb=function(a){return!0===k.aff_domains[a]||(null===k.aff_domains[a]||void 0===k.aff_domains[a])&&Zb&&!T(a)};var $a=function(a){var b;if(!a)return!1;var c=a.toLowerCase().split(/\s+/);a=Sa?[Sa.toLowerCase()]:[];a=a.concat(Wc);
var d=0;for(b=c.length;d<b;d++){var e=c[d];if(0<=id.call(a,e))return!0}return!1};var uc=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1};var tc=function(a){return-1===a.indexOf("#slm-")||(a=a.split("#slm-"),2!==a.length||isNaN(a[1])||10*parseInt(a[1])!==10*a[1])?null:parseInt(a[1])};var Aa=function(a,b){var c;--n.skimlinks_requests_in_flight;var d=null!=a?a:{};a&&(k.beacon.push(d),z.publish("beacon",d));d.country&&(la.country=d.country);d.guid&&
""===h.cookie&&(h.cookie=d.guid);d.sessid&&""===h.sessid&&(h.sessid=d.sessid);k.waypointDomain=Ab(h.cookie);var e=d.merchant_domains||[];var f=0;for(c=e.length;f<c;f++){var g=e[f];T(g)||(k.aff_domains[g]=!0)}for(g in k.aff_domains)null===k.aff_domains[g]&&(k.aff_domains[g]=!1);cc&&(g=h.cookie,Ob&&g&&fa("https://o.skimresources.com/"+Ob+"/profile/"+g+"?callback=skimlinksODPCallback",!1,{}));if(Wb)for(e=da(),g=0,f=e.length;g<f;g++)c=e[g],jd(c);return z.publish(b,d)};var jd=function(a){var b=u(a,"rel");
var c=M(a.hostname);if(!b&&c&&!0===k.aff_domains[c])return u(a,"rel","nofollow")};n.skimlinksODPCallback=function(a){var b=a.status;a=a.actions;a=void 0===a?[]:a;b&&"OK"===b&&ja(a,function(a){var b=a.url;"pixel"===a.action&&ib(b)})};var oc=function(a,b){var c,d;null==b&&(b=k.callback_name);n.skimlinks_requests_in_flight=(null!=(c=n.skimlinks_requests_in_flight)?c:0)+1;if(null==a||!a.length)return n[b](),!1;c=t('{"pubcode":"'+A+'","domains":_DOMAIN_LIST_,"page":"'+n.location.href+'"}');var e="//r.skimresources.com/api/?callback="+
b+(v?"&dnt=1":"")+(B?"&fdnt=1":"")+"&data="+c;c="msie"===h.detect.browser?2E3:8E3;var f=[];var g=0;for(d=a.length;g<d;g++){var w=a[g];f.push(w);e.replace("_DOMAIN_LIST_",t(x(f))).length>c&&(f=f.slice(0,-1))}e=e.replace("_DOMAIN_LIST_",t(x(f)));return fa(e,!1,{})};var K=function(){return q.addEventListener?function(a,b,c){var d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:!1;if(a&&(a.nodeName||a===n))return a.addEventListener(b,c,d)}:function(a,b,c){if(a&&(a.nodeName||a===n))return a.attachEvent("on"+
b,function(){return 7>h.detect.version&&!n.event?(setTimeout(function(){return c.call(a,n.event)},100),!0):c.call(a,n.event)})}}();var mc=function(a){var b;if(ac){var c=M(a.hostname);if(c in Qa)return c="[&?]"+Qa[c].name+"=(http[^&]+)",c=new RegExp(c),decodeURIComponent(null!=(b=a.href)?b.match(c).pop():void 0)||a.href}return a.href};var nc=function(a,b){var c=h.referrer?"&pref="+t(h.referrer):"";var d=!1;if(0<b.indexOf("#slm-")){var e=b.split("#slm-");2!==e.length||isNaN(e[1])||10*parseInt(e[1])!==
10*e[1]||(b=e[0],d=e[1])}var f=u(a,"data-skimlinks-tracking")||na;var g=u(a,"data-skimlinks-editor")&&1===parseInt(u(a,"data-skimlinks-editor"))?1:0;if(I(a,"skimwords-link")){var w=u(a,"data-skimwords-word");e=u(a,"data-skim-creative");var m=u(a,"data-skim-product");var l=k.waypointDomain;b=l+"/?id="+A+(f?"&xcust="+f:"")+(!1!==d?"&xs=9":"&xs=2")+"&url="+t(b)+"&xguid="+h.cookie+"&xuuid="+h.uuid+"&xsessid="+h.sessid+"&isjs=1&xword="+(w?w:"")+"&xcreo="+(e?e:"")+"&xpid="+(m?m:"")+"&xed="+g+"&sref="+t(n.location)+
c+(v?"&dnt=1":"")+(B?"&fdnt=1":"")+(!1!==d?"&slmcid="+d:"")+(!1!==h.timezone?"&xtz="+h.timezone:"")}else I(a,"skimlinks-inline")?(e=u(a,"data-skim-creative"),b=k.waypointDomain+"/?id="+A+(G?"&site="+G:"")+(aa?"&test="+aa:"")+(f?"&xcust="+f:"")+(!1!==d?"&xs=9":"&xs=8")+"&isjs=1&url="+t(b)+"&xguid="+h.cookie+"&xuuid="+h.uuid+"&xsessid="+h.sessid+"&xcreo="+(a&&null!=e?e:0)+"&xed="+g+"&sref="+t(n.location)+"&pref="+t(h.referrer)+(v?"&dnt=1":"")+(B?"&fdnt=1":"")+(!1!==d?"&slmcid="+d:"")+(!1!==h.timezone?
"&xtz="+h.timezone:"")):N(a,"noskimlinks")||(e=u(a,"data-skim-creative"),b=k.waypointDomain+"/?id="+A+(G?"&site="+G:"")+(aa?"&test="+aa:"")+(f?"&xcust="+f:"")+(!1!==d?"&xs=9":"&xs=1")+"&isjs=1&url="+t(b)+"&xguid="+h.cookie+"&xuuid="+h.uuid+"&xsessid="+h.sessid+"&xcreo="+(a&&null!=e?e:0)+"&xed="+g+"&sref="+t(n.location)+c+(v?"&dnt=1":"")+(B?"&fdnt=1":"")+(!1!==d?"&slmcid="+d:"")+(!1!==h.timezone?"&xtz="+h.timezone:""));0<Ta.length&&(b+="&"+Ta);h.isAdblockUser&&!N(a,"noskimlinks")&&(b+="&abp=1");return b};
var kd={}.hasOwnProperty;var ld=function(a,b){var c;var d=[];J&&(a.xrf=1);for(c in a)if(kd.call(a,c)){var e=a[c];"data"!==c&&d.push(c+"="+e)}a.data&&d.push("data="+a.data);return b+"?"+d.join("&")};var md=function(a){var b=q.getElementsByTagName("body")[0];var c=q.createElement("img");c.src=a;c.width=1;c.height=1;"undefined"!==typeof c.style&&(c.style.display="none");b.appendChild(c);return c};var cb=function(a,b){nd(a);H&&u(a,"target",H);var c=u(a,"onclick");var d="click"===b.type||"contextmenu"===
b.type;if(null!=c&&-1!==c.toString().indexOf("return false")){if(d)return d=xa(b),ba(b),(H?n.open(d.href):n.open(d.href,H)).focus()}else return ba(b)};var lc=function(a){var b=xa(a);var c=b.href;var d=V(c);T(d)&&(c=od(b,c));""===h.cookie&&Yb?cb(b,a):(a=c,d=V(a),T(d)||(d="",c=u(b,"data-skimlinks-tracking")||na,0<a.indexOf("#slm-")&&(b=a.split("#slm-"),2!==b.length||isNaN(b[1])||10*parseInt(b[1])!==10*b[1]||(a=b[0],d=b[1])),b={call:"track",data:t('{"pubcode":"'+A+'", "referrer":"'+n.location+'", "pref":"'+
h.referrer+'", "site":"'+G+'", "url":"'+a+'", "custom":"'+(c||"")+'", "xtz":'+h.timezone+', "uuid":"'+h.uuid+'", "slmcid":"'+d+'", "product":"1"}')},v&&(b.dnt=v),B&&(b.fdnt=1),b=ld(b,"//t.skimresources.com/api/"),b=b+"&rnd="+Math.random(),md(b)));return!0};var dc=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return dc(a,b-1,c)}};var jc=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=dc(function(){return a.parentNode},3,null),null==a)return null;return a};var kc=
function(a){return a in Qa};var od=function(a,b){var c=pd(b);c!==b&&(gb(a),hb(a,c));return c};var pd=function(a){return a=h.cookie?a.replace(/([&\?]{1})xguid=([a-fA-F0-9]{32})/,"$1xguid="+h.cookie):a.replace(/([&\?]{1}xguid=[a-fA-F0-9]{32})/,"")};var nd=function(a){var b,c;var d=l("skimlinks_strip_attribute",!1);if(!d)return!1;for(c in d)if(C(d,c)){var e=d[c];(b=u(a,c))&&0===b.indexOf(e)&&(b=b.substr(e.length),u(a,c,b))}return!0};var L=function(){if(k.has_been_called)return!1;k.has_been_called=!0;
return ca(jb(),"skimlinksBeaconSecondaryCallback")};var qd=function(){if(h.skimlinksEnabled){var a=jb();ca(a);a:if(a=q){var b=Hc(ic,200);try{Xb&&K(a,"mouseup",b,!0),K(a,"click",b,!0),K(a,"auxclick",b,!0),K(a,"contextmenu",b,!0),K(a,"touchstart",b,!0)}catch(c){a=!1;break a}a=!0}else a=!1;return a}};z.on("skim_js_start",function(){n.skimlinks_revenue_forecast=window.skimlinks_revenue_forecast=!1;k.tracking&&!/^[a-z0-9_\\|]+$/i.test(k.tracking)&&(k.tracking=!1);if(J&&l("skimlinks"))return!1;qd();var a=
function(){if(k.has_been_called)return!0;try{q.documentElement.doScroll("left")}catch(d){return setTimeout(a,50),!1}return L()};var b=function(){return function(){return q.addEventListener?function(){q.removeEventListener("DOMContentLoaded",b,!1);L();return!0}:q.attachEvent?function(){q.detachEvent("onreadystatechange",b);L();return!0}:function(){L();return!0}}}(this)();if("complete"===q.readyState)return setTimeout(L,1);if(q.addEventListener)return q.addEventListener("DOMContentLoaded",b,!1),n.addEventListener("load",
L,!1);if(q.attachEvent){q.attachEvent("onreadystatechange",b);n.attachEvent("onload",L);var c=!1;try{c=null===n.frameElement}catch(d){}if(q.documentElement.doScroll&&c)return a()}});null==n.skimlinksBeaconCallback&&(n.skimlinksBeaconCallback=rc);null==n.skimlinksBeaconSecondaryCallback&&(n.skimlinksBeaconSecondaryCallback=qc);null==n.skimlinksBeaconAuxCallback&&(n.skimlinksBeaconAuxCallback=pc);var ec={}.hasOwnProperty;var fc=0;var qa=!1;var ra={};var gc=function(a){var b;return a&&-1!==a.indexOf("class=")?
(b=a.match(/([^\[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a:a};var rd=function(a){ra[a]=ra[a]||0;ra[a]++;return a+"_"+ra[a]};var Va=function(a){var b;var c=b=null;if(-1!==a.indexOf(".")){a=a.split(".");var d=a[0];c=a[1]}else-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],b=a[1].split("]"),b=b[0]):d=a;return{tag:d,id:b,"class":c}};
var sa=function(a,b){var c;var d=b.split(",");var e=0;for(c=d.length;e<c;e++){b=d[e];b=y(b);b=Va(b);var f=!0;var g=(g="string"===typeof a.className?a.className:"")||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";var h=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";!b.tag||a.nodeName&&a.nodeName.toLowerCase()===b.tag||(f=!1);b["class"]&&(!g||g!==b["class"]&&0!==g.indexOf(b["class"]))&&(f=!1);b.id&&(!h||h!==b.id&&-1===h.indexOf(b.id))&&(f=!1);if(f)return!0}return!1};
var sd=function(a){var b,c;if("undefined"!==typeof document.querySelectorAll)return document.querySelectorAll(a);var d=[];a=Va(a);if(a.tag&&a["class"]){var e=document.getElementsByTagName(a.tag);var f=0;for(b=e.length;f<b;f++){var g=e[f];(c=g.className||g.getAttribute("class"))&&0===c.indexOf(a["class"])&&d.push(g)}}else a.tag&&a.id?(g=document.getElementById(a.id))&&g.nodeName.toLowerCase()===a.tag&&d.push(g):(a=a.tag,d=document.getElementsByTagName(a));return d};var td=function(a,b,c){var d,e;var f=
[];if("undefined"!==typeof a.querySelectorAll)f=a.querySelectorAll(b);else if(b=Va(b),b.tag&&b["class"]){if(!a.getElementsByTagName)return c?[]:!1;var g=a.getElementsByTagName(b.tag);var h=0;for(d=g.length;h<d;h++)if(a=g[h],(e=a.className||a.getAttribute("class"))&&0===e.indexOf(b["class"]))if(c)f.push(a);else return!0}else if(b.tag&&b.id){if((a=document.getElementById(b.id))&&a.nodeName&&a.nodeName.toLowerCase()===b.tag)if(c)f.push(a);else return!0}else b=b.tag,f=a.getElementsByTagName(b);return c?
f:0<f.length};var ud=function(a){var b=a.offsetWidth;a=a.offsetHeight;return 468===b&&60===a||234===b&&60===a||728===b&&90===a||300===b&&250===a||250===b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};var vd=function(){var a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");a.push("div.ad_container");
a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");-1!==n.location.href.indexOf(".google.")?(a.push("td.gac_c"),a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):-1!==n.location.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==n.location.href.indexOf(".aol.")?
(a.push("div.sllLink"),a.push("div.n")):-1!==n.location.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),a.push("div.sb_adsWv2"),a.push("div.sb_adsNv2"),a.push("div[class*=sb_ads]"));return a};var wd=function(a){var b;var c={};var d=0;for(b=a.length;d<b;d++){var e=a[d];c[e]=!0}return c};var F=function(){var a={};return{traverse:function(b,c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,f,g;if(qa)return a;
qa=!0;var h=this.get_exclude_selector(c);var k=this.get_exclude_selector([]);c=h.selector;h=h.needed;k=k.selector;0===b.length&&b.push("body");b=b.concat(d);var m=0;for(f=b.length;m<f;m++){var l=b[m];l=gc(l);l=sd(l);var n=e=0;for(g=l.length;e<g;n=++e)n=l[n],this.traverse_node(n,h,k,c,d)}return a},traverse_node:function(b,c,d,e,f){var g=[];var k=0;for(g.push({node:b,tagName:"",readOnly:!1,parent_id:null});k<g.length;)!(b=g[k].node)||ud(b)||N(b,"noskimwords",!0)||c&&""!==d&&sa(b,d)||(g[k].readOnly=
!1,b.nodeName&&b.nodeName!==Pa?(g[k].tagName=b.nodeName,null!==g[k].parent_id&&(g[k].readOnly=g[g[k].parent_id].readOnly),g[k].readOnly||(c&&sa(b,e)?g[k].readOnly=!0:La(f,b.nodeName.toLowerCase())&&(g[k].readOnly=!0)),La(f,b.nodeName.toLowerCase())&&(g[k].readOnly=!0)):null!==g[k].parent_id&&(g[k].tagName=g[g[k].parent_id].tagName,g[k].readOnly=g[g[k].parent_id].readOnly),"msie"===h.detect.browser&&9>h.detect.version&&g[k].readOnly||(b.hasChildNodes()?g=this.add_child_nodes(g[k],k,g):this._add(b,
!1,g[k].tagName,g[k].readOnly))),k++;return a},is_traversed:function(){return qa},is_good_tag:function(a){return wd("p body div span ul ol li table tbody td tr th tfoot col colgroup em strong big small blockquote cite b dl dfn dd dt ins form legend noframes pre noscript center font i article section main".split(" "))[a.nodeName.toLowerCase()]?!0:!1},is_html:function(a){return(a=y(a))&&"<"===a[0]},get_non_colliding_nodes:function(){var b;var c=a;var d={};fc=0;for(b in c)ec.call(c,b)&&(d[b]=c[b],fc++);
return d},get_as_hash_node_dict:function(){var b;var c={};for(b in a){var d=a[b];C(a,b)&&(c[b]=d)}return c},get_as_pair_array:function(){var b;var c=[];for(b in a)ec.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var b,e,f;var g=[];if(!c){c=document.getElementsByTagName("body");if(!c.length)return{needed:!1,selector:""};c=c[0]}a=a.concat(vd());var h=b=0;for(e=a.length;b<e;h=++b)a[h]=gc(a[h]);b=!1;e="";var k=0;for(f=a.length;k<f;k++)h=a[k],td(c,h,!1)&&g.push(h);g.length&&
(b=!0,e=g.join(",").replace("class=","class^="));return{needed:b,selector:e}},length:function(){return ka(a).length},reset:function(){a=[];return qa=!1},add_child_nodes:function(a,c,d){var b,f;var g=a.node.childNodes;var h=0;for(f=g.length;h<f;h++)(b=g[h])&&b.nodeName&&!this._add(b,!1,a.tagName,a.readOnly)&&this.is_good_tag(b)&&d.push({node:b,tagName:a.tagName,readOnly:a.readOnly,parent_id:c});return d},add_node:function(a,c){return this._add(a,c)},_add:function(b,c,d,e){var f=null;b.nodeName===Pa&&
(f=y(b.nodeValue));c=c||!1;if("msie"===h.detect.browser&&9>h.detect.version&&e)return!1;if("msie"!==h.detect.browser||9<=h.detect.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(g){}if(f&&!this.is_html(f)&&3<=f.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(f,c);if(!c)return!1;a[c]=b}return f?!0:!1},_skim_id_hash:function(a){if(!a)return"";var b=y(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,"");b=""+b+":"+a.substring(0,20);return b=rd(b)}}}();var Mc=function(a,b,c){if(J)return!1;
var d=(a.data?a.data:a.childNodes[0].data).replace(b.repl_regex,b.replacement);var e=document.createElement("span");b=document.createDocumentFragment();e.innerHTML=d;if("msie"===h.detect.browser&&9>h.detect.version){d=a.previousSibling;var f=/^\s/;d&&d.nodeValue&&d.nodeValue.length&&f.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=" ");(d=a.nextSibling)&&d.nodeValue&&d.nodeValue.length&&f.test(d.nodeValue[0])&&(d.nodeValue=" "+d.nodeValue)}for(;e.firstChild;)e.firstChild.nodeName===Pa?(d=
b.appendChild(e.firstChild),F.add_node(d)):(d=b.appendChild(e.firstChild),null===d||c||Xa(d,!0));if(c=a.parentNode)return c.replaceChild(b,a)};var Nc=function(a){K(a,"click",ba);$b||K(a,"contextmenu",ba);return Xa(a,!1)};var xd=function(a,b,c,d){var e=qb(a);var f="";k.target&&(f='target="'+k.target+'"');b=Ma(b);e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a='$1$2<a href="'+b+'" class="'+d+'" '+f+' data-skimwords-word="'+encodeURIComponent(Ma(a))+
('"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6');b=e.replace(/\?:/g,"");return{search_regex:new RegExp(e,"i"),repl_regex:new RegExp(b,"i"),repl_text:a}};var Jc=function(a,b){var c,d,e;if(!a||Wa(a,["span.skimlinks-unlinked"]))return[[],[]];var f=a.data;var g=[];var k=[];for(d=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig;c=d.exec(f);){var l=c[0];if("link.phrase"!==l){var m=c.index;if(0<y(l).length&&-1===l.indexOf("/.")&&-1===l.indexOf("...")){var n=
l;0!==l.indexOf("http")&&0!==l.indexOf("//")&&(n="msie"===h.detect.browser&&6>=h.detect.version?"http://"+l:"//"+l);c=V(n);var q=hc({OriginalPhrase:""+l,Url:n,Title:"",ActionType:2,GroupId:0,Unlinked:!0});(e=xd(""+l,n,ma.creative,"skimlinks-unlinked"))&&k.push({start:m,text:""+Ma(l),domain:c,repl_regex:e.repl_regex,replacement:e.repl_text,regex:e.search_regex,phrase:q,link:n});g.push(c)}else break}}if(k.length){var p=b;n="skimlinks-unlinked";var t;l=document.createDocumentFragment();var r=0;c=[];
m=a.nodeValue;d=[];f=a.parentNode;n||(n="skimwords-potential");p||(p="-1");if(f){q=0;for(t=k.length;q<t;q++){var v=k[q];var x=document.createElement("span");x.className=n;e=document.createTextNode(m.substring(r,v.start));l.appendChild(e);x.innerHTML=v.text;l.appendChild(x);r={};r.node=x;r.match=v;u(r,"occurrence",v.target_occurrence);c.push(r);r=v.start+v.text.length;d.push(e);F.add_node(e,p)}k=document.createTextNode(m.substring(r));d.push(k);l.appendChild(k);F.add_node(k,p);f.replaceChild(l,a)}p=
[c,d];k=p[0];p=p[1];l=0;for(d=k.length;l<d;l++)f=k[l],ma.url_spans.push(f)}p||(p=[]);return[g,p]};var Kc=function(a){var b;if(k.exclude.length){var c=k.exclude;var d=0;for(b=c.length;d<b;d++){var e=c[d];if(e===a)return!1}}if(k.include.length){c=k.include;d=0;for(b=c.length;d<b;d++)if(e=c[d],e===a)return!0;return!1}return!0};z.on("skim_js_init",function(){if(h.unlinkedEnabled){var a="beacon_callback_post_page_load",b=Ib;h.skimwordsEnabled&&(a="instant_api_callback_settings",b=Ic);z.on(a,b);z.on("dom_changed",
Jb);z.on("beacon_callback_aux",Lc)}});var Na=!1,Q=!1,Y=null,Z=null,yd={detect:function(a){a:{try{var b=navigator.userAgent.toLowerCase();if(-1===b.indexOf("firefox")&&-1===b.indexOf("chrome")){Q=!0;Na=!1;break a}}catch(c){}b=""+11*Math.random();Y=new Image;Y.onload=Lb;Y.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"1").replace(/\*/,b);Z=new Image;Z.onload=Lb;Z.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"2").replace(/\*/,b)}Kb(a,250)}};(function(){if(!n.__SKIM_JS_GLOBAL__){n.__SKIM_JS_GLOBAL__=
{getDebugInfo:Sc};if(Qc(k.hostname)||Ua&&Oc(Ua))h.skimlinksEnabled=!1,h.skimwordsEnabled=!1,h.unlinkedEnabled=!1;"msie"===h.detect.browser&&8>=h.detect.version&&(h.skimwordsEnabled=!1);yd.detect(function(a){h.isAdblockUser=a});z.publish("skim_js_init");z.publish("skim_js_start")}})()})();
