var _tmr=_tmr||[];
(function(){function l(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function r(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function G(a){(new Image).src=m(a,!0,!1,!1)+";e="+escape("detect")}function d(){}function H(a){if(!s&&"id"in a&&"type"in a&&("pageView"==a.type||"reachGoal"==a.type||"sendEvent"==a.type))s=a.id}function A(a){return a||"https:"==document.location.protocol?"https:":"http:"}function U(a){return(a=
!t?void 0:t[a])&&B?a-B:void 0}function m(a,b,c,e){var d="id"in a?a.id:s,f="url"in a?a.url:location.href,g="referrer"in a?a.referrer:document.referrer,h="title"in a?a.title:document.title;b=A(p)+"//top-fwz1.mail.ru"+(b?"/tracker":"/counter")+"?js=13"+(d?";id="+escape(d):"")+(f?";u="+escape(f):"")+(g?";r="+escape(g):"")+("start"in a&&0<a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+("pid"in a?";pid="+escape(a.pid):"")+(e&&h?";title="+
encodeURIComponent(h):"")+((C=window.screen)?";s="+C.width+"*"+C.height:"")+";vp=";d=e=0;document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?(e=document.documentElement.clientWidth,d=document.documentElement.clientHeight):"number"==typeof window.innerWidth&&(e=window.innerWidth,d=window.innerHeight);b=b+(""+e+"*"+d)+";touch="+V+";hds="+W+";flash="+D+";sid="+I+";ver="+J;if(c){if(!t||!E)c="";else{c=[];c.push(E.type);c.push(E.redirectCount);c.push(B);
for(e=0;e<K.length;e++)c.push(U(K[e]));c=c.join("/")}c=";nt="+c}else c="";return b+c+("device"in a?";device="+escape(a.device):"")+";_="+Math.random()}function L(a,b){return A(p)+"//top-fwz1.mail.ru/tracker?js=13;id="+a[0]+";e="+escape(b)+";sid="+I+";ids="+a.join()+";ver="+J+";_="+Math.random()}function X(){if(!M)for(var a=0;a<n.length;a++){var b=n[a];(new Image).src=m(b,!0,!1,!0)+";e="+escape("PVT/15")}}function Y(){if(!N&&!u){u=!0;for(var a=0;a<n.length;a++)G(n[a])}}function v(){document.addEventListener?
(r(document,"DOMContentLoaded",v),_tmr.onready()):document.attachEvent&&"complete"===document.readyState&&(r(document,"readystatechange",v),_tmr.onready())}function O(){r(window,"load",O);_tmr.onready();_tmr.onload()}function w(){r(window,"unload",w);r(window,"beforeunload",w);_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var g=window,f=navigator,C,u=!1,Z=function(){function a(a){var c=document.createElement("div");c.setAttribute("class",String.fromCharCode(112,117,98,
95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,109,101,100,105,117,109,95,114,101,99,116,97,110,103,108,101,95,51,48,48,95,50,53,48,32,112,117,98,95,55,50,56,120,57,48,32,108,101,97,100,101,114,98,111,97,114,100,95,55,50,56,95,57,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,95,54,48,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,120,54,48,48,32,116,101,120,116,45,97,100,32,116,101,120,116,65,100,32,116,101,120,116,95,
97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,97,100,95,116,101,120,116,32,97,100,95,116,101,120,116,32,98,97,110,110,101,114,95,116,101,120,116,32,116,101,120,116,45,98,97,110,110,101,114));c.setAttribute("style","position: absolute !important; top: -1000px !important; left: -10000px !important; width: 1px !important; height: 1px !important;");this.bait=document.body.appendChild(c);this.bait.offsetParent;this.bait.offsetHeight;
this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fn=a||null;var e=this;setTimeout(function(){e._checkBait.call(e)},1)}a.prototype._checkBait=function(){if(u)this._stop();else{var a=!1;null!==document.body.getAttribute("abp")||null===this.bait.offsetParent||0==this.bait.offsetHeight||0==this.bait.offsetLeft||0==this.bait.offsetTop||0==this.bait.offsetWidth||0==this.bait.clientHeight||0==this.bait.clientWidth?a=!0:void 0!==
window.getComputedStyle&&(a=window.getComputedStyle(this.bait,null),a="none"==a.getPropertyValue("display")||"hidden"==a.getPropertyValue("visibility"));(!0===a||10<=++this.loopNumber)&&this._stop();if(a&&this.fn)try{this.fn()}catch(c){}else if(!a&&10>this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},50*this.loopNumber)}}};a.prototype._stop=function(){try{document.body.removeChild(this.bait)}catch(a){}};return function(b){new a(b)}}(),J=60,x=[],F=0,y=0,I="xxxxxxxx".replace(/[x]/g,
function(a){return(16*Math.random()|0).toString(16)}),z=0,s=0,n=[],h=[],k="string"===typeof location.hostname&&(-1!=location.hostname.search(/^odnoklassniki\.ru$/)||-1!=location.hostname.search(/\.odnoklassniki\.ru$/)||-1!=location.hostname.search(/^ok\.ru$/)||-1!=location.hostname.search(/\.ok\.ru$/)),p="string"===typeof location.hostname&&(-1!=location.hostname.search(/^vk\.com$/)||-1!=location.hostname.search(/\.vk\.com$/)),P=k||p,M=k||p,$=k||p,Q=k||p,N=!1,V="ontouchstart"in g||1<(f.maxTouchPoints||
f.msMaxTouchPoints)?"1":"0",W=window.devicePixelRatio||0,D="";if(f.plugins&&f.plugins["Shockwave Flash"])D=f.plugins["Shockwave Flash"].description.split(" ")[2];else if(window.ActiveXObject)try{var q=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),q=q.GetVariable("$version"),q=q.split(" ")[1].split(","),D=q[0]+"."+q[1]}catch(aa){}var g=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},t=g.timing||{},E=g.navigation||{},K="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
B=!t?void 0:t.navigationStart;d.prototype.pageView=function(a){"start"in a&&x.push(a);(new Image).src=m(a,!1,!1,!0);y=(new Date).getTime()};d.prototype.reachGoal=function(a){if("goal"in a&&a.goal){var b="";"value"in a&&a.value&&(b=parseInt(a.value)||"");(new Image).src=m(a,!0,!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal))}};d.prototype.itemView=function(a){if("id"in a||s)(new Image).src=A(0)+"//ad.mail.ru/retarget/?counter="+(a.id||s)+"&list="+(a.list||"")+"&productid="+(a.productid||"")+"&pagetype="+
(a.pagetype||"")+"&totalvalue="+(a.totalvalue||0)+"&_="+Math.random()};d.prototype.sendEvent=function(a){if("category"in a&&a.category&&"action"in a&&a.action){var b=a.category.substr(0,300),c=a.action.substr(0,300),e="";"label"in a&&a.label&&(e=a.label.substr(0,300));var d="";"value"in a&&a.value&&(d=parseInt(a.value)||"");b="CE:"+d+"/"+b.replace(/;/g," ")+";"+c.replace(/;/g," ")+";"+e.replace(/;/g," ");(new Image).src=m(a,!0,!1,!1)+(";e="+escape(b))}};d.prototype.processEvent=function(a){if("type"in
a&&("pageView"!=a.type||"id"in a)){H(a);var b;if(b="id"in a&&"type"in a)if(b="pageView"==a.type)if(b=5>h.length){b:{for(b=0;b<h.length;b++)if(h[b]===a.id){b=!0;break b}b=!1}b=!b}b&&(h.push(a.id),n.push(a),u&&G(a));switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a)}}};d.prototype.push=function(a){this.processEvent(a)};var R=!1;d.prototype.onready=function(){R||(R=!0,!N&&!u&&Z(Y))};
var S=!1;d.prototype.onload=function(){if(!S){S=!0;if(!$&&0<x.length){z=(new Date).getTime();for(var a=0,b;b=x[a];a++)(new Image).src=m(b,!0,!0,!1)+";e="+escape("RT/load")+";et="+z;y=z;x=[]}M||setTimeout(X,15E3)}};d.prototype.beat=function(){if(!P&&0!=h.length&&F){var a=(new Date).getTime(),b=a-F;if(!(12E4<b)){if(12E4<a-y)for(var c=0;c<n.length;c++){var e=n[c];(new Image).src=m(e,!0,!1,!0)+";e="+escape("RT/resend")+";et="+z+";active="+(b?"1":"0")}else(new Image).src=L(h,"RT/beat");y=a}}};var T=!1;
d.prototype.unload=function(){T||(T=!0,!Q&&0<h.length&&((new Image).src=L(h,"RT/unload")))};d.prototype.activity=function(a){F=(new Date).getTime()};g=new d;for(f=0;k=_tmr[f];f++)H(k);for(f=0;k=_tmr[f];f++)g.processEvent(k);_tmr=g;if("complete"===document.readyState||"loading"!==document.readyState&&!document.documentElement.doScroll)_tmr.onready();else document.addEventListener?l(document,"DOMContentLoaded",v):document.attachEvent&&l(document,"readystatechange",v);if("complete"===document.readyState)_tmr.onload();
else l(window,"load",O);Q||(l(window,"unload",w),l(window,"beforeunload",w));if(!P&&0<h.length){setInterval(_tmr.beat,3E4);try{g=function(a){function b(a){l(document,a,function(){_tmr.activity(a)})}for(var c=0;c<a.length;c++)b(a[c])},g(["scroll","gesturechange","touchmove"]),g(["mousedown","mousemove","mouseup"]),l(window,"scroll",function(){_tmr.activity("scallback")})}catch(ba){}}}})();

